Update README.md
Remove `--target` argument, which triggers the following error:
```
thread 'main' panicked at 'Unable to parse command-line arguments: unused arguments left: --target', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-espflash-0.1.2/src/main.rs:13:
29    
```